### ISSUE TITLE
Please clarify license/copyright situation

### ISSUE THREAD

**Issue by lamby** [eriknellessen/gpg-encrypted-root#1]
Hi @eriknellessen,

Just wondering whether you could clarify the copyright/licensing situation of this repository? :)

Best wishes,

— @lamby

**Comment by eriknellessen** [comment]
Hi @lamby ,
thanks for your message. As Peter Lebbing wrote most of the code and I just adapted it to GPGv2, I asked him for his opinion. He said that the scripts are just modified versions of the scripts in the Debian Wheezy Cryptsetup package. He thinks that this has been licensed as GPL-2+.
I am not an expert for licenses. All I know is that if the original source has been licensed under a GPL license, the modified code also has to be licensed under a GPL license. Peter and I are both fine with that. I think the question is whether to take GPL-2+ or GPL-3+.
So @lamby , can you tell me what options we have and if there is a preferred solution to this?
Kind regards,
Erik

**Comment by lamby** [comment]
GPL-2+ is easiest and works for me. Please just drop that in a README.md or similar into the root of this repo :)

**Comment by eriknellessen** [comment]
Alright, I opened a pull request including the license file and a remark in the README.md: #2. Please provide some feedback if everything is fine like that.

**Comment by eriknellessen** [comment]
Solved in #2.
